version: "3.8"
services:
  posts:
    build:
      context: ./posts
    command: npm start
    ports:
      - "4000:4000"
    develop:
      watch:
        - action: sync
          path: ./posts
          target: /src/web
          ignore:
            - node_modules/
        - action: rebuild
          path: ./posts/package.json