version: "3.8"
services:
  posts:
    build:
      context: ./posts
    command: npm start
    ports:
      - "4000:4000"
    develop:
      watch:
        - action: sync
          path: ./posts/index.js
          target: /usr/src/app/index.js
          ignore:
            - node_modules/
        - action: rebuild
          path: ./posts/package.json
  comments:
    build:
      context: ./comments
    command: npm start
    ports:
      - "4001:4001"
    develop:
      watch:
        - action: sync
          path: ./comments
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./comments/package.json