services:
  web:
    build: ..
    command: npm start
    develop:
      watch:
        - action: sync
          path: ./posts
          target: /src/web
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json